### ISSUE TITLE
Script failed on password with backquote ` p

### ISSUE THREAD

**Issue by zamentur** [scith/odoo_ynh#8]
Hi,
I got this when I was trying to install odoo.
```bash
sudo yunohost app install https://github.com/zamentur/odoo_ynh
Téléchargement...
Extraction...
Terminé.
Choisissez un domaine pour Odoo (Odoo sera installé dans sa racine !) : xxxxxxxxx
Quelle version d'Odoo souhaitez-vous installer ? (8.0|9.0) (default: 8.0) : 9.0
Choisissez un mot de passe maître fort pour l'administration : M.k8.`<f\l|gxx~
Choisissez un mot de passe pour le compte 'admin' d'Odoo : YJeIMS2s"~H$*&*
Choisissez une langue pour Odoo (en_US|fr_FR|de_DE) (default: en_US) : fr_FR
Attention : sh: 1: Syntax error: EOF in backquote substitution
```
Thanks

**Comment by scith** [comment]
Hi, did you put a backquote in the master admin password "`"?
If so, the problem might come from there...

**Comment by zamentur** [comment]
Yes, you can see the password "M.k8.`<f\l|gxx~" . Of course before to publish the password, I changed it on my server...
May be I will create a fix.

**Comment by scith** [comment]
If you know how to that would be kind... I don't know how to escape such characters in bash.
Does the installation work with a password that does not have such characters?

**Comment by zamentur** [comment]
With my fixes yes, the installation works: https://github.com/zamentur/odoo_ynh
I am testing it.

**Comment by scith** [comment]
Cool! Don't hesitate to pull request :)
For wkhtmltopdf, I installed from source instead of package because someone in another issue had a problem with the package I don't know why...
---
The following packages have unmet dependencies:
wkhtmltox : Depends: xfonts-base but it is not going to be installed
Depends: xfonts-75dpi but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
---

But then wkhtmltox from source created another problem for someone else with a 32bits instance...

**Comment by scith** [comment]
I've merged your fork
Thanks for the work :+1:
